### ISSUE TITLE
Error interacting with agent after it has been removed

### ISSUE THREAD

**Issue by Ne0nd0g** [Ne0nd0g/merlin#46]
### Prerequisite
* [X] I have read the [README](https://github.com/Ne0nd0g/merlin/blob/master/README.MD)
* [X] I have search the opened & _closed_ [issues](https://github.com/Ne0nd0g/merlin/issues)
* [X] I have search the [WIKI](https://github.com/Ne0nd0g/merlin/wiki) and its [FAQ](https://github.com/Ne0nd0g/merlin/wiki/FAQ) page
### Environment Data
* Merlin Version: `0.6.6.BETA`
* Merlin Build: `nonRelease`
* Go Version: `1.11.2`
* GOPATH Environment Variable:
* GOROOT Environment Variable:
* Operating System: `Ubuntu`

### Expected Behavior
Show agent information
### Actual Behavior
>panic: runtime error: invalid memory address or nil pointer dereference
### Steps to Reproduce Behavior
Instruct an agent to exit by  issuing the `kill` command from the agent menu. Immediately try to interact with that again after it has been removed by issuing the `info` command.
### Misc Information
```
Merlin» sessions 

+--------------------------------------+-------------+------+--------+-------------+--------+
|              AGENT GUID              |  PLATFORM   | USER |  HOST  |  TRANSPORT  | STATUS |
+--------------------------------------+-------------+------+--------+-------------+--------+
| 8caa6f6c-0a56-466e-acfc-519d487fb2fe | linux/amd64 | tim  | ABC001 | HTTP/2 (h2) | Active |
+--------------------------------------+-------------+------+--------+-------------+--------+

Merlin» interact 8caa6f6c-0a56-466e-acfc-519d487fb2fe 
Merlin[agent][8caa6f6c-0a56-466e-acfc-519d487fb2fe]» [i]Agent 8caa6f6c-0a56-466e-acfc-519d487fb2fe was removed from the server
Merlin[agent][8caa6f6c-0a56-466e-acfc-519d487fb2fe]» info
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xe0 pc=0x5944ba]

goroutine 20 [running]:
github.com/Ne0nd0g/merlin/pkg/agents.GetAgentStatus(0x6e46560a6c6faa8c, 0xfeb27f489d51fcac, 0xc000079800, 0x43455c)
        /home/tim/go/src/github.com/Ne0nd0g/merlin/pkg/agents/agents.go:549 +0x6a
github.com/Ne0nd0g/merlin/pkg/agents.ShowInfo(0x6e46560a6c6faa8c, 0xfeb27f489d51fcac)
        /home/tim/go/src/github.com/Ne0nd0g/merlin/pkg/agents/agents.go:291 +0x77
github.com/Ne0nd0g/merlin/pkg/cli.Shell()
        /home/tim/go/src/github.com/Ne0nd0g/merlin/pkg/cli/cli.go:363 +0x1617
created by main.main
        /home/tim/go/src/github.com/Ne0nd0g/merlin/cmd/merlinserver/main.go:67 +0x481
exit status 2

```

**Comment by Ne0nd0g** [comment]
Not sure when I fixed it, but it _should_ be resolved:

```
Merlin[agent][6e5b203e-4a4c-4ef2-a0aa-9c6b91c28fc8]» kill
[-]Created job xuqyKzmMGa for agent 6e5b203e-4a4c-4ef2-a0aa-9c6b91c28fc8 at 2020-05-03T17:33:17Z
Merlin» interact 6e5b203e-4a4c-4ef2-a0aa-9c6b91c28fc8 
Merlin[agent][6e5b203e-4a4c-4ef2-a0aa-9c6b91c28fc8]» [i]Agent 6e5b203e-4a4c-4ef2-a0aa-9c6b91c28fc8 was removed from the server
Merlin[agent][6e5b203e-4a4c-4ef2-a0aa-9c6b91c28fc8]» 
Merlin[agent][6e5b203e-4a4c-4ef2-a0aa-9c6b91c28fc8]» info
[!]6e5b203e-4a4c-4ef2-a0aa-9c6b91c28fc8 is not a valid agent!
Merlin[agent][6e5b203e-4a4c-4ef2-a0aa-9c6b91c28fc8]» cmd id
[!]invalid agent ID
Merlin[agent][6e5b203e-4a4c-4ef2-a0aa-9c6b91c28fc8]» 
```
